Feature/improve loopback control
deltacasttv/ue-media-plugin pull request #3
Opened 2024-04-23 15:02 UTC by Nathoufresh

2024-04-24 06:17 UTC, julienalofs requested changes

2024-04-24 06:17 UTC, julienalofs commented on Source/DeltacastMedia/Private/Deltacast/DeltacastSdk.cpp
>  void FDeltacastSdk::SetByPassRelay(const VHDHandle BoardHandle, const VHD::ULONG PortIndex, const VHD::ULONG LinkCount, const int Value)
Should be renamed to SetLoopbackState

2024-04-24 13:21 UTC, julienalofs approved these changes

2024-04-30 09:53 UTC, julienalofs commented
@Nathoufresh Did you test VideoMaster API backward compatibility? We need to be sure that the plugin works correctly with old VideoMaster API

2024-05-03 11:45 UTC, Nathoufresh commented
> @Nathoufresh Did you test VideoMaster API backward compatibility? We need to be sure that the plugin works correctly with old VideoMaster API

Tested on 6.24 & 6.25

2024-05-03 11:51 UTC, merged